### ISSUE TITLE
Change the top image on the website

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths-website#14]
Update the image
New one: https://www.figma.com/design/Ps6e2qMWEaV0a47waFExf8/Race-of-Sloths-(New)?node-id=2842-4789&t=AVGoQhbL2z05UHh2-1

**Comment by rubycop** [comment]
![Screenshot 2024-09-04 111901](https://github.com/user-attachments/assets/bcde0da0-75a8-46ba-8d4f-d66a1ba6e0a8)
![Screenshot 2024-09-04 111853](https://github.com/user-attachments/assets/ee58becd-de25-4098-8d44-ca363c508396)
